services:
  postgres:
    image: postgres:16
    container_name: postgres_grpmcc_voting
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votacion
    ports:
      - "10.147.17.101:5433:5432"
    volumes:
      - /opt/swarch/grpmcc/central/config/db/postgres:/var/lib/postgresql/data
    networks:
      - voting_network_grpmcc

networks:
  voting_network_grpmcc:
    driver: bridge