services:
  postgres:
    image: postgres:16
    container_name: postgres_icegrid
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: votacion
    ports:
      - "5433:5432"
