//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingProxy.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Proxy;

public class VotingSystemUnavailableException extends com.zeroc.Ice.UserException
{
    public VotingSystemUnavailableException()
    {
        this.reason = "";
    }

    public VotingSystemUnavailableException(Throwable cause)
    {
        super(cause);
        this.reason = "";
    }

    public VotingSystemUnavailableException(String reason)
    {
        this.reason = reason;
    }

    public VotingSystemUnavailableException(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::Proxy::VotingSystemUnavailableException";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Proxy::VotingSystemUnavailableException", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -7937614426364059335L;
}
