//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Votation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class AlreadyVotedException extends com.zeroc.Ice.UserException
{
    public AlreadyVotedException()
    {
    }

    public AlreadyVotedException(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::Demo::AlreadyVotedException";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Demo::AlreadyVotedException", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -6783582248899595975L;
}
