//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Votation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class VotingSystemException extends com.zeroc.Ice.UserException
{
    public VotingSystemException()
    {
        this.reason = "";
    }

    public VotingSystemException(Throwable cause)
    {
        super(cause);
        this.reason = "";
    }

    public VotingSystemException(String reason)
    {
        this.reason = reason;
    }

    public VotingSystemException(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::Demo::VotingSystemException";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Demo::VotingSystemException", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -8507700272068258476L;
}
